annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.1.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Kubewatch is a Kubernetes watcher that currently publishes notification to Slack. Run it in your k8s cluster, and you will get event notifications in a slack channel.
engine: gotpl
home: https://github.com/robusta-dev/kubewatch
icon: https://bitnami.com/assets/stacks/kubewatch/img/kubewatch-stack-220x234.png
keywords:
  - kubernetes
  - slack
  - hipchat
  - mattermost
  - flock
  - msteams
  - webex
maintainers: []
name: kubewatch
sources:
  - https://github.com/robusta-dev/kubewatch
version: 3.5.0
