apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  .kubewatch.yaml: |
    handler:
      {{- if .Values.slack.enabled }}
      slack: {{- toYaml .Values.slack | nindent 8 }}
      {{- end }}
      {{- if .Values.slackwebhook.enabled }}
      slackwebhook: {{- toYaml .Values.slackwebhook | nindent 8 }}
      {{- end }}
      {{- if .Values.hipchat.enabled }}
      hipchat: {{- toYaml .Values.hipchat | nindent 8 }}
      {{- end }}
      {{- if .Values.mattermost.enabled }}
      mattermost: {{- toYaml .Values.mattermost | nindent 8 }}
      {{- end }}
      {{- if .Values.flock.enabled }}
      flock: {{- toYaml .Values.flock | nindent 8 }}
      {{- end }}
      {{- if .Values.webhook.enabled }}
      webhook: {{- toYaml .Values.webhook | nindent 8 }}
      {{- end }}
      {{- if .Values.webex.enabled }}
      webex: {{- toYaml .Values.webex | nindent 8 }}
      {{- end }}
      {{- if .Values.cloudevent.enabled }}
      cloudevent: {{- toYaml .Values.cloudevent | nindent 8 }}
      {{- end }}
      {{- if .Values.smtp.enabled }}
      smtp: {{- toYaml .Values.smtp | nindent 8 }}
      {{- end }}
      {{- if .Values.msteams.enabled }}
      msteams: {{- toYaml .Values.msteams | nindent 8 }}
      {{- end }}
      {{- with .Values.extraHandlers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.lark.enabled }}
      lark: {{- toYaml .Values.lark | nindent 8 }}
      {{- end }}
    resource: {{- toYaml .Values.resourcesToWatch | nindent 6 }}
    customresources: {{- toYaml .Values.customresources | nindent 6 }}
    namespace: {{ .Values.namespaceToWatch | quote }}
